/**
 * «СИМУЛЯТОР ФИНТЕХА» — the movement and money simulation, in the browser.
 *
 * THIS IS A SECOND IMPLEMENTATION OF ONE RULE, and this project's own rules say
 * not to build one. It exists because client-side prediction is impossible
 * without it: to move the instant a thumb pushes, the browser has to compute the
 * same thing the server would have.
 *
 * WHAT MAKES IT SAFE. `internal/gamefintech/sim.go` is the authority; this is the
 * port. They are pinned together by golden vectors — the Go test emits a desk
 * layout, an input transcript and the resulting player trace into
 * `internal/gamefintech/testdata/step_vectors.json`, and `fintechStep.spec.ts`
 * asserts this file reproduces it. Change the rule on one side and the gate goes
 * red on the other. **Do not edit this file without regenerating the vectors and
 * reading them.**
 *
 * It is statement-for-statement the Go, deliberately, down to the order of the
 * eight operations — a port that reads as a translation can be checked against
 * its original by eye, and one that reads as a rewrite cannot. Two consequences
 * are worth stating here so they are never "fixed" by mistake:
 *
 *   * A DASH EARNS NOTHING. You are not standing still, so nothing accrues.
 *   * A DASH KEEPS THE STREAK. You were never really working, so the ramp is not
 *     reset and the grace window is not touched.
 *
 * That asymmetry is the whole skill ceiling of the game. It is not an oversight
 * in either direction.
 *
 * THE SERVER REMAINS THE ONLY AUTHORITY. Nothing here decides anything. When
 * this disagrees with a snapshot, the snapshot wins, unconditionally.
 */

import type { FintechConfig, FintechRect } from '../api/types';

/**
 * How much of a push counts as movement at all.
 *
 * MIRRORED RATHER THAN SERVED, and it is the one constant of the simulation the
 * catalogue does not publish (`GET /config` carries the speeds, the rates, the
 * dash and the boss, but not this). It is the threshold `moving` is tested
 * against, so the port cannot be written without it — and a client that guessed
 * a different one would disagree with the server about whether a barely-touched
 * stick resets the streak, which is exactly the disagreement a correction cannot
 * smooth over.
 *
 * If the server ever retunes it, this is the line that has to move with it, and
 * the golden vectors are what will say so.
 */
export const IDLE_THRESHOLD = 0.05;

/**
 * The longest sub-step the server will simulate, in seconds.
 *
 * ALSO MIRRORED RATHER THAN SERVED — `GET /config`'s `move` block carries the
 * send rate and the per-frame command cap but not this. It is `Sanitise`'s
 * clamp on `dt`, so the port needs it for the same reason it needs the idle
 * threshold: a client that predicted from an unclamped command would disagree
 * with the server about every hostile or merely unlucky input.
 */
export const MAX_STEP_SECONDS = 0.2;

/** The constants the simulation runs on. Everything but the two above is served. */
export interface StepConstants {
  /** The floor, in metres. A player is clamped to [r, w-r] × [r, h-r]. */
  officeW: number;
  officeH: number;
  playerRadius: number;
  walkSpeed: number;
  dashSpeed: number;
  dashSeconds: number;
  dashCooldownSeconds: number;
  /** What a slowed walk is multiplied by. See sim.go's SlowFactor. */
  slowFactor: number;
  idleThreshold: number;
  maxStepSeconds: number;
  basePerSecond: number;
  rampSeconds: number;
  maxMultiplier: number;
  graceSeconds: number;
}

/** One sub-step of input. Mirrors the server's Command. */
export interface StepCommand {
  /** Assigned by the predictor when it applies the command, not by the caller. */
  seq?: number;
  dt: number;
  mx: number;
  my: number;
  /** A dash was asked for on this sub-step. Absent means no. */
  dash?: boolean;
}

/** The simulated player. Mirrors the server's Player, minus what we never predict. */
export interface StepPlayer {
  x: number;
  y: number;
  /** Roubles earned so far. Predicted, but the HUD reads the snapshot's. */
  salary: number;
  /** Seconds of accumulated stillness. */
  streak: number;
  /** Seconds spent moving inside the grace window. */
  moveGrace: number;
  /** Seconds of dash remaining. */
  dashLeft: number;
  /** Seconds until the dash is available again. */
  dashCooldown: number;
  /**
   * Seconds of Claude Code's slow remaining.
   *
   * PREDICTED, and it is the only one of that iteration's values that had to be:
   * it MULTIPLIES THE WALK, so a client that did not know about it would predict
   * 6.4 m/s while the office moved the same player at 5.12 — 1.28 m/s of
   * divergence, past the snap threshold in about 1.6 s of walking, which is a
   * figure yanked backwards ten times a second while a thumb is held down. The
   * cloud and the persona are on the Occupant precisely because `step` never
   * reads them; this one it does.
   */
  slowLeft: number;
  /**
   * The direction the current dash committed to, unit length, captured when it
   * started.
   *
   * A DASH IS A COMMITTED MOVEMENT, not "move fast while holding the stick".
   * The commonest dash in this game is tapped from a standstill, where exactly
   * one command carries a direction and the rest of the burst carries no input
   * at all — so a per-command dash covered a fraction of its distance, and a
   * different fraction on each end of the port, which the correction then
   * yanked back. See the Go original in sim.go.
   */
  dashDx: number;
  dashDy: number;
}

/** Reads the simulation constants off the served catalogue. */
export function stepConstants(config: FintechConfig): StepConstants {
  return {
    officeW: config.office.w,
    officeH: config.office.h,
    playerRadius: config.office.player_radius,
    walkSpeed: config.move.walk_speed,
    dashSpeed: config.move.dash_speed,
    dashSeconds: config.move.dash_ms / 1000,
    dashCooldownSeconds: config.move.dash_cooldown_ms / 1000,
    // Served rather than mirrored, because it is content: a percentage the
    // cheatsheet also prints, so a retune moves both together. Falls back to 1 —
    // no slow at all — rather than to a guess, so an older catalogue simply
    // predicts an unslowed walk instead of diverging by a made-up factor.
    slowFactor: (config.claude?.slow_pct ?? 100) / 100,
    idleThreshold: IDLE_THRESHOLD,
    maxStepSeconds: MAX_STEP_SECONDS,
    basePerSecond: config.money.base_per_second,
    rampSeconds: config.money.ramp_seconds,
    maxMultiplier: config.money.max_multiplier,
    graceSeconds: config.money.grace_ms / 1000,
  };
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}

function clampFinite(v: number, lo: number, hi: number): number {
  if (Number.isNaN(v)) return 0;
  return clamp(v, lo, hi);
}

/**
 * Clamps a command into the range the server is willing to simulate.
 *
 * Mirrors `Sanitise` in `internal/gamefintech/sim.go`, which the server calls in
 * `Office.Enqueue` — never in `Step`. The port calls it INSIDE `step` instead,
 * so there is no path into the simulation that skips it, and so the client
 * predicts from exactly the command the server will run rather than from the one
 * it happened to send. A correction that arrives on every frame is
 * indistinguishable from a broken game, and an unsanitised prediction produces
 * one for every diagonal push.
 *
 * A diagonal must not be faster than a straight line, and normalising only when
 * the vector is longer than one keeps a half-pushed stick analogue — which
 * matters on a phone, where the stick is the only control there is.
 */
export function sanitise(c: StepCommand, k: StepConstants): StepCommand {
  let mx = clampFinite(c.mx, -1, 1);
  let my = clampFinite(c.my, -1, 1);
  const mag = Math.hypot(mx, my);
  if (mag > 1) {
    mx /= mag;
    my /= mag;
  }
  const out: StepCommand = { dt: clampFinite(c.dt, 0, k.maxStepSeconds), mx, my };
  if (c.seq !== undefined) out.seq = c.seq;
  if (c.dash) out.dash = true;
  return out;
}

/**
 * Moves a disc clear of one desk, along its nearest edge.
 *
 * The whole collision model, and it is deliberately the simplest thing that
 * works: every desk is an axis-aligned rectangle, so a circle overlapping one is
 * pushed out along whichever of the four edges it is least far past. That gives
 * sliding along a desk edge and a clean stop at a corner with no special cases —
 * and it is what makes bumping into furniture tactically useful rather than a
 * pathfinding problem, because the boss is pushed out by the same function and
 * does not route around anything.
 *
 * ONE PASS PER DESK, IN CATALOGUE ORDER, exactly as the server does it. Order
 * matters where two desks are close enough to overlap after expansion by the
 * radius; the catalogue's own order is the tie-break, on both sides.
 */
function pushOutOfDesk(d: FintechRect, px: number, py: number, r: number): { x: number; y: number } {
  const x0 = d.x - r;
  const y0 = d.y - r;
  const x1 = d.x + d.w + r;
  const y1 = d.y + d.h + r;
  if (px <= x0 || px >= x1 || py <= y0 || py >= y1) return { x: px, y: py };

  const left = px - x0;
  const right = x1 - px;
  const up = py - y0;
  const down = y1 - py;
  const least = Math.min(left, right, up, down);
  // Strict comparisons in a fixed order, so a tie resolves the same way in both
  // implementations rather than by whichever branch happened to be written first.
  if (least === left) return { x: x0, y: py };
  if (least === right) return { x: x1, y: py };
  if (least === up) return { x: px, y: y0 };
  return { x: px, y: y1 };
}

/**
 * Advances one player by one command. Pure — no clock, no randomness, no state.
 *
 * Mirrors `Step` in `internal/gamefintech/sim.go`, in the same eight steps and the
 * same order, preceded by the `Sanitise` the server runs in `Enqueue` — see
 * `sanitise` above for why the port folds the two together and the original does
 * not. The golden vectors carry RAW commands and their trace is of
 * `Step(Sanitise(cmd))`, which is exactly this.
 */
export function step(
  desks: readonly FintechRect[],
  p: StepPlayer,
  raw: StepCommand,
  k: StepConstants,
): StepPlayer {
  const c = sanitise(raw, k);
  const out: StepPlayer = { ...p };
  const dt = c.dt;

  // 1. Dash start. Refused while one is running or while the cooldown holds, so
  //    a player mashing the button gets exactly one dash per cooldown.
  if (c.dash && out.dashCooldown <= 0 && out.dashLeft <= 0) {
    out.dashLeft = k.dashSeconds;
    out.dashCooldown = k.dashCooldownSeconds;
    // The direction is captured HERE, once, and the whole dash runs on it — see
    // the Go original, sim.go. A dash tapped from a standstill has exactly one
    // command carrying a direction and no input at all for the rest of its
    // duration, so a dash steered per-command covered a fraction of its distance
    // and a DIFFERENT fraction on each end of the port.
    const mag = Math.hypot(c.mx, c.my);
    out.dashDx = mag > 0 ? c.mx / mag : 0;
    out.dashDy = mag > 0 ? c.my / mag : 0;
  }

  // Captured BEFORE the timers are decremented: a dash that starts on this very
  // sub-step is running for the whole of it, which is what makes the first
  // frame of a dash as fast and as free as the rest of it.
  const dashing = out.dashLeft > 0;

  // 2. Timers.
  out.dashLeft = Math.max(0, out.dashLeft - dt);
  out.dashCooldown = Math.max(0, out.dashCooldown - dt);
  out.slowLeft = Math.max(0, out.slowLeft - dt);

  // 3. Speed, and — while dashing — the DIRECTION too. The command's axes are
  //    ignored for the duration: the dash goes where it committed.
  //
  //    THE SLOW MULTIPLIES THE WALK AND NOT THE DASH, exactly as the Go original
  //    does: the dash is the answer to being caught, and a slowed dash would take
  //    away the way out of the punishment.
  const speed = dashing
    ? k.dashSpeed
    : out.slowLeft > 0
      ? k.walkSpeed * k.slowFactor
      : k.walkSpeed;
  const mx = dashing ? out.dashDx : c.mx;
  const my = dashing ? out.dashDy : c.my;

  // 4. Move, then the floor, then every desk. That order is the specification:
  //    the floor clamp can put a player against a wall and a desk push can move
  //    them along it, and doing it the other way round lets a corner desk push
  //    somebody through the wall behind it.
  let px = out.x + mx * speed * dt;
  let py = out.y + my * speed * dt;
  const r = k.playerRadius;
  px = clamp(px, r, k.officeW - r);
  py = clamp(py, r, k.officeH - r);
  for (const d of desks) {
    const pushed = pushOutOfDesk(d, px, py, r);
    px = pushed.x;
    py = pushed.y;
  }
  out.x = px;
  out.y = py;

  // 5. Idle test. The magnitude of the push, not the distance travelled — a
  //    player walking into a desk is still working the stick, and still not
  //    earning.
  const moving = Math.hypot(c.mx, c.my) > k.idleThreshold;

  // 6. The streak — the rule the whole game rests on.
  if (dashing) {
    // The one movement that costs nothing: preserved, and not grown either.
    // MoveGrace is deliberately left alone, so a dash in the middle of a walk
    // neither spends the grace window nor refills it.
  } else if (moving) {
    out.moveGrace += dt;
    if (out.moveGrace > k.graceSeconds) {
      out.streak = 0;
      // Clamped rather than left to grow, so a long walk does not bank a debt
      // that would have to be paid off before the next step counts.
      out.moveGrace = k.graceSeconds;
    }
  } else {
    out.moveGrace = 0;
    out.streak += dt;
  }

  // 7. Money. The multiplier reads the streak AFTER step 6 has moved it, which
  //    is why the two are in this order and not the other one.
  const mult = 1 + (k.maxMultiplier - 1) * Math.min(out.streak / k.rampSeconds, 1);
  if (!moving && !dashing) {
    out.salary += k.basePerSecond * mult * dt;
  }

  // 8.
  return out;
}

/**
 * The multiplier a streak is worth, on its own.
 *
 * Exported because the HUD draws the ramp as a bar and the cheatsheet states its
 * ceiling, and both would otherwise re-derive the arithmetic beside the one
 * inside `step`. Same expression, one place.
 */
export function multiplierFor(streakSeconds: number, rampSeconds: number, max: number): number {
  if (!(rampSeconds > 0)) return max;
  const t = Math.min(Math.max(streakSeconds, 0) / rampSeconds, 1);
  return 1 + (max - 1) * t;
}
