/**
 * «ВАНЯДУМ» — the movement simulation, in the browser.
 *
 * THIS IS A SECOND IMPLEMENTATION OF ONE RULE, and this project's own rules say
 * not to build one. It exists because client-side prediction is impossible
 * without it: to apply your own input the instant you press it, the browser has
 * to compute the same thing the server would have (ADR-052).
 *
 * WHAT MAKES IT SAFE. `internal/gamevanyadum/sim.go` is the authority; this is
 * the port. They are pinned together by golden vectors — the Go test emits a
 * level, an input transcript and the resulting position trace into
 * `internal/gamevanyadum/testdata/step_vectors.json`, and
 * `vanyadumStep.spec.ts` asserts this file reproduces it. Change movement on
 * one side and the gate goes red on the other. **Do not edit this file without
 * regenerating the vectors and reading them.**
 *
 * It is line-for-line the Go, deliberately, down to the order of the clamps and
 * the shape of the collision loop. Where it would be more idiomatic in
 * TypeScript to do something else, it does the Go thing instead — a port that
 * reads as a translation can be checked against its original by eye, and one
 * that reads as a rewrite cannot.
 *
 * THE SERVER REMAINS THE ONLY AUTHORITY. Nothing here decides anything. When
 * this disagrees with a snapshot, the snapshot wins, unconditionally.
 */

import type { VanyadumLevel, VanyadumSector, VanyadumWall } from './vanyadumLevel';

/** The constants the simulation runs on, as the catalogue serves them. */
export interface StepConstants {
  walkSpeed: number;
  radius: number;
  maxStep: number;
  maxPitch: number;
  maxStepSeconds: number;
  collisionPasses: number;
}

/** One sub-step of input. Mirrors the server's Command. */
export interface StepCommand {
  seq?: number;
  dt: number;
  mx: number;
  my: number;
  yaw: number;
  pitch: number;
}

/** The simulated player. Mirrors the server's Player, minus what we never predict. */
export interface StepPlayer {
  x: number;
  y: number;
  yaw: number;
  pitch: number;
  sector: number;
}

/** Squared epsilon used where the Go uses 1e-9. Kept identical on purpose. */
const EPS = 1e-9;

function clampFinite(v: number, lo: number, hi: number): number {
  if (Number.isNaN(v)) return 0;
  return Math.max(lo, Math.min(hi, v));
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}

/**
 * Clamps a command into the range the server is willing to simulate.
 *
 * Applied here as well as on the server, and identically, because a client that
 * predicted from an unclamped command would disagree with the server about
 * every hostile or merely unlucky input — and a correction that arrives on
 * every frame is indistinguishable from a broken game.
 */
export function sanitise(c: StepCommand, k: StepConstants): StepCommand {
  let yaw = c.yaw;
  if (Number.isNaN(yaw) || !Number.isFinite(yaw)) yaw = 0;
  yaw = yaw % (Math.PI * 2);
  return {
    seq: c.seq,
    dt: clampFinite(c.dt, 0, k.maxStepSeconds),
    mx: clampFinite(c.mx, -1, 1),
    my: clampFinite(c.my, -1, 1),
    yaw,
    pitch: clampFinite(c.pitch, -k.maxPitch, k.maxPitch),
  };
}

/** The sector containing a point, or −1. Mirrors the server's SectorAt exactly. */
export function sectorAt(level: VanyadumLevel, x: number, y: number): number {
  for (const s of level.sectors) {
    if (x >= s.x0 && x <= s.x1 && y >= s.y0 && y <= s.y1) return s.id;
  }
  return -1;
}

function sectorById(level: VanyadumLevel, id: number): VanyadumSector | undefined {
  return level.sectors.find((s) => s.id === id);
}

/**
 * Moves a disc clear of one wall if it is inside it.
 *
 * `from` is where the player was before the step, used only to break the
 * degenerate tie when the centre lands exactly on the segment — anything but a
 * division by zero, which would put him at infinity.
 */
function pushOut(
  w: VanyadumWall,
  px: number,
  py: number,
  fromX: number,
  fromY: number,
  radius: number,
): { x: number; y: number; moved: boolean } {
  let cx: number;
  let cy: number;
  if (w.v) {
    cx = w.a;
    cy = clamp(py, w.lo, w.hi);
  } else {
    cx = clamp(px, w.lo, w.hi);
    cy = w.a;
  }
  let dx = px - cx;
  let dy = py - cy;
  let d = Math.hypot(dx, dy);
  if (d >= radius) return { x: px, y: py, moved: false };
  if (d < EPS) {
    if (w.v) {
      dx = fromX - w.a;
      dy = 0;
      if (dx === 0) dx = 1;
    } else {
      dx = 0;
      dy = fromY - w.a;
      if (dy === 0) dy = 1;
    }
    d = Math.hypot(dx, dy);
  }
  const scale = radius / d;
  return { x: cx + dx * scale, y: cy + dy * scale, moved: true };
}

/**
 * Moves a disc from one point towards another, sliding along whatever it meets.
 *
 * The whole collision model is "push the circle out of every solid segment it
 * overlaps, a few times" — enough here because every wall is axis-aligned, and
 * it gives wall-sliding, doorway jambs and inside corners with no special cases.
 */
function resolve(
  level: VanyadumLevel,
  fromX: number,
  fromY: number,
  fromSector: number,
  toX: number,
  toY: number,
  k: StepConstants,
): { x: number; y: number; sector: number } {
  let px = toX;
  let py = toY;
  for (let pass = 0; pass < k.collisionPasses; pass++) {
    let moved = false;
    for (const w of level.walls) {
      const out = pushOut(w, px, py, fromX, fromY, k.radius);
      if (out.moved) {
        px = out.x;
        py = out.y;
        moved = true;
      }
    }
    if (!moved) break;
  }

  // Two ways the move is refused outright rather than adjusted, both mirroring
  // the server: leaving the level at all means the resolver has been defeated,
  // and standing still is always a safe answer where teleporting into the void
  // is not; and a rise taller than MaxStep is the ordinary rule.
  const id = sectorAt(level, px, py);
  if (id < 0) return { x: fromX, y: fromY, sector: fromSector };
  const to = sectorById(level, id);
  const from = sectorById(level, fromSector);
  if (to && from && Math.abs(to.fz - from.fz) > k.maxStep + EPS) {
    return { x: fromX, y: fromY, sector: fromSector };
  }
  return { x: px, y: py, sector: id };
}

/**
 * Advances one player by one command. Pure — no clock, no randomness, no state.
 *
 * Mirrors `Step` in `internal/gamevanyadum/sim.go`. The command is sanitised
 * here rather than by the caller, so there is no path into the simulation that
 * skips it — the same promise the server makes.
 */
export function step(
  level: VanyadumLevel,
  p: StepPlayer,
  cmd: StepCommand,
  k: StepConstants,
): StepPlayer {
  const c = sanitise(cmd, k);
  const out: StepPlayer = { ...p, yaw: c.yaw, pitch: c.pitch };

  // The movement axes are in the player's own frame, so yaw turns them into the
  // world. Yaw zero looks along +Y; the renderer's camera uses the same
  // convention and the golden vectors pin it, because the two disagreeing looks
  // like broken controls rather than like a broken transform.
  const sin = Math.sin(out.yaw);
  const cos = Math.cos(out.yaw);
  let dx = c.my * sin + c.mx * cos;
  let dy = c.my * cos - c.mx * sin;

  // A diagonal must not be faster than a straight line. Normalising only when
  // the vector is longer than one keeps a half-pressed stick analogue.
  const mag = Math.hypot(dx, dy);
  if (mag > 1) {
    dx /= mag;
    dy /= mag;
  }
  if (dx === 0 && dy === 0) return out;

  const dist = k.walkSpeed * c.dt;
  const r = resolve(level, p.x, p.y, p.sector, p.x + dx * dist, p.y + dy * dist, k);
  out.x = r.x;
  out.y = r.y;
  out.sector = r.sector;
  return out;
}

/**
 * Where an eye sits for somebody standing in this sector. Mirrors `EyeZ`.
 *
 * Takes the sector rather than a whole player because it has two callers that
 * hold different things: the predictor knows the player it is simulating, and
 * the peer decode knows only the sector index the wire named — a peer's height
 * is no longer sent, precisely so the client can look it up here (see
 * vanyadumRoster). Both of them must land on the same number as the server, and
 * one function is how that stays true.
 *
 * Predicted rather than taken from the snapshot for the same reason the
 * position is: a camera height that only changed twenty times a second would
 * make every step visibly jolt.
 *
 * A sector nothing matches is the eye height alone, exactly as the server's own
 * bounds check answers.
 */
export function eyeZ(level: VanyadumLevel, sector: number, eyeHeight: number): number {
  const s = sectorById(level, sector);
  return (s ? s.fz : 0) + eyeHeight;
}
