-- 010_game_vanyadum: the entire durable footprint of «ВАНЯДУМ» (game 3).
--
-- One table, and it is a summary rather than a world. Everything else about a
-- run lives in memory for the few minutes it takes to play:
--
--   * The LEVEL is a pure function of `seed`, generated by internal/gamevanyadum
--     at run start. Storing geometry would store something reproducible from
--     eight bytes, and would freeze a generator that is going to change every
--     iteration for the next month.
--   * The ARENA — where the player is standing, what he has picked up, which
--     tick it is — is deliberately ephemeral, and is lost on restart in exactly
--     the way the realtime hub's presence is. A run is a few minutes long and a
--     lost one costs a replay. This is what keeps the game's 20 Hz simulation
--     clear of the rule that nothing in this project ticks durable state.
--
-- What is deliberately NOT here, each because it would make content cost a
-- migration:
--
--   * No `game_key` column. The table name carries the game's identity — that is
--     the whole point of the naming convention, and a discriminator column would
--     be a second, weaker copy of it.
--   * No enums for anything. Pickups, surfaces and the level's shape are a Go
--     catalogue (content.go), so a new pickup is a deploy and never an
--     ALTER TYPE.
--   * No per-pickup or per-event rows. A run that recorded every beer would be
--     an event log for a joke shooter, and the summary below answers every
--     question anybody has asked of it.
--   * No art table. This game stores no art at all: geometry, textures, sprites
--     and sound are generated from the seed on the client, so the shared
--     game_assets store is not used and no blob is uploaded for it, ever.

CREATE TABLE IF NOT EXISTS game_vanyadum_runs (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id  uuid NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,

    -- The seed the level was generated from. Kept so two people can compare
    -- times over the same заброшка, which is the only thing that would make a
    -- leaderboard worth looking at. Eight bytes to keep that possible.
    seed        bigint NOT NULL,

    -- Whether the run was finished rather than abandoned, how long it took, and
    -- how much beer was collected on the way. `beer` is a plain column rather
    -- than a bag of counters: there is one pickup today, and a JSONB column
    -- added in advance of a second one would be complexity bought against a
    -- requirement that does not exist yet.
    success     boolean NOT NULL DEFAULT false,
    seconds     integer NOT NULL DEFAULT 0,
    beer        integer NOT NULL DEFAULT 0,

    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);

-- The only read: an account's own recent runs, newest first. It exists so that a
-- human can confirm in production that a run was written without opening a
-- database.
CREATE INDEX IF NOT EXISTS game_vanyadum_runs_account_idx
    ON game_vanyadum_runs (account_id, created_at DESC)
    WHERE deleted_at IS NULL;
