package gamevanyadum

import (
	"encoding/json"
	"flag"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// The conformance vectors that pin the TypeScript port of Step.
//
// WHY THIS FILE EXISTS. Client-side prediction means the browser runs the same
// movement and collision the server does, so `Step` now exists twice — in Go
// and in TypeScript. That is a second implementation of one rule, which this
// project's rules tell you not to build, and it is accepted here only because
// prediction is impossible without it (ADR-052). What makes it *safe* rather
// than merely permitted is this: the Go implementation emits a trace, the
// TypeScript one has to reproduce it, and the two diverging is a red test in
// the ordinary gate rather than a player walking through a wall another player
// can see.
//
// The file carries the LEVEL as well as the trace, because the client is never
// allowed to generate a level (ADR-050) — so the vectors hand it the same
// sector graph the server would have sent, and the port is tested on exactly
// the input it will see in production.
//
// Regenerate with:
//
//	./dev.sh test -run TestGoldenVectors ./internal/gamevanyadum/ -update
//
// Doing so deliberately breaks the TypeScript test until the port is brought
// back into line. That is the point: a change to movement is a change to two
// files, and this is what refuses to let it be a change to one.

var updateGolden = flag.Bool("update", false, "rewrite the golden vectors from the current Step")

// goldenPath is where the vectors live. Under testdata/ so `go build` ignores
// it, and read by the vitest suite through a relative path.
func goldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "step_vectors.json")
}

type goldenFile struct {
	// Note is for a human who opens the file wondering what it is.
	Note      string          `json:"note"`
	Constants goldenConstants `json:"constants"`
	Cases     []goldenCase    `json:"cases"`
}

// goldenConstants are the numbers the port must be using. They are in the file
// so that a mismatch reports "your walk speed is wrong" rather than a hundred
// failing positions.
type goldenConstants struct {
	WalkSpeed       float64 `json:"walk_speed"`
	Radius          float64 `json:"radius"`
	MaxStep         float64 `json:"max_step"`
	MaxPitch        float64 `json:"max_pitch"`
	MaxStepSeconds  float64 `json:"max_step_seconds"`
	CollisionPasses int     `json:"collision_passes"`
}

type goldenCase struct {
	Name  string `json:"name"`
	Level *Level `json:"level"`
	// Start is where the walk begins, so a case can be aimed at a doorway
	// rather than starting wherever the generator put the spawn.
	Start    Vec2          `json:"start"`
	Sector   int           `json:"sector"`
	Commands []goldenCmd   `json:"commands"`
	Trace    []goldenPoint `json:"trace"`
}

type goldenCmd struct {
	Dt    float64 `json:"dt"`
	MX    float64 `json:"mx"`
	MY    float64 `json:"my"`
	Yaw   float64 `json:"yaw"`
	Pitch float64 `json:"pitch"`
}

type goldenPoint struct {
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	Sector int     `json:"s"`
}

// buildGolden runs every case through the real Step and returns the file.
//
// The cases are chosen to exercise the parts of the port most likely to be got
// wrong, rather than to be many: a plain walk, a wall slide, a doorway
// traversal with a step up, a long pseudo-random wander that will find corners
// nobody thought of, and a hostile command that must be clamped identically on
// both ends.
func buildGolden() goldenFile {
	f := goldenFile{
		Note: "Generated by TestGoldenVectors in internal/gamevanyadum. " +
			"Pins the TypeScript port of Step (web/src/lib/vanyadumStep.ts) to the Go original. " +
			"Regenerate with: ./dev.sh test -run TestGoldenVectors ./internal/gamevanyadum/ -update",
		Constants: goldenConstants{
			WalkSpeed:       WalkSpeed,
			Radius:          PlayerRadius,
			MaxStep:         MaxStep,
			MaxPitch:        MaxPitch,
			MaxStepSeconds:  MaxStepSeconds,
			CollisionPasses: collisionPasses,
		},
	}

	const dt = 1.0 / SimHz

	// A generated level, walked in a slowly turning spiral. This is the case
	// that finds the corners: six hundred steps through a real заброшка will
	// press into jambs, slide along walls and cross doorways in both
	// directions.
	for _, seed := range []int64{7, 101} {
		l := Generate(seed)
		p := NewPlayer(l)
		c := goldenCase{
			Name:   "wander",
			Level:  l,
			Start:  p.Pos,
			Sector: p.Sector,
		}
		yaw := 0.0
		for i := 0; i < 300; i++ {
			yaw += 0.37
			cmd := goldenCmd{Dt: dt, MY: 1, Yaw: yaw}
			c.Commands = append(c.Commands, cmd)
			p = Step(l, p, Command{Dt: cmd.Dt, MX: cmd.MX, MY: cmd.MY, Yaw: cmd.Yaw})
			c.Trace = append(c.Trace, goldenPoint{X: p.Pos.X, Y: p.Pos.Y, Sector: p.Sector})
		}
		f.Cases = append(f.Cases, c)
	}

	// A hand-built pair of rooms with a step in the doorway, walked straight at
	// it. Deterministic, small, and the one case whose expected outcome a human
	// can check by reading it.
	{
		l := &Level{
			Sectors: []Sector{
				{ID: 0, MinX: 0, MinY: 0, MaxX: 10, MaxY: 10, FloorZ: 0, CeilZ: CeilingHeight},
				{ID: 1, MinX: 10, MinY: 0, MaxX: 20, MaxY: 10, FloorZ: 0.3, CeilZ: 0.3 + CeilingHeight},
			},
			Portals: []Portal{{A: 0, B: 1, Vertical: true, At: 10, Lo: 4, Hi: 6}},
		}
		l.Walls = buildWalls(l)
		p := NewPlayer(l)
		p.Pos, p.Sector = Vec2{X: 2, Y: 5}, 0
		c := goldenCase{Name: "doorway-and-step", Level: l, Start: p.Pos, Sector: p.Sector}
		for i := 0; i < 120; i++ {
			cmd := goldenCmd{Dt: dt, MY: 1, Yaw: math.Pi / 2} // due +X
			c.Commands = append(c.Commands, cmd)
			p = Step(l, p, Command{Dt: cmd.Dt, MY: cmd.MY, Yaw: cmd.Yaw})
			c.Trace = append(c.Trace, goldenPoint{X: p.Pos.X, Y: p.Pos.Y, Sector: p.Sector})
		}
		f.Cases = append(f.Cases, c)
	}

	// Hostile input. Both ends must clamp identically, or a client predicts one
	// thing from a command the server reads as another and the correction never
	// settles.
	{
		l := &Level{Sectors: []Sector{{ID: 0, MinX: 0, MinY: 0, MaxX: 20, MaxY: 20, FloorZ: 0, CeilZ: CeilingHeight}}}
		l.Walls = buildWalls(l)
		p := NewPlayer(l)
		p.Pos, p.Sector = Vec2{X: 10, Y: 10}, 0
		c := goldenCase{Name: "hostile-clamping", Level: l, Start: p.Pos, Sector: p.Sector}
		hostile := []goldenCmd{
			{Dt: 1e6, MY: 1e6, Yaw: 0},
			{Dt: -5, MY: 1, Yaw: 1},
			{Dt: dt, MX: 50, MY: -50, Yaw: 100},
			{Dt: dt, MX: 0.5, MY: 0.5, Yaw: -3},
			{Dt: 0.5, MY: 1, Yaw: 2, Pitch: 99},
		}
		for _, cmd := range hostile {
			c.Commands = append(c.Commands, cmd)
			p = Step(l, p, Command{Dt: cmd.Dt, MX: cmd.MX, MY: cmd.MY, Yaw: cmd.Yaw, Pitch: cmd.Pitch})
			c.Trace = append(c.Trace, goldenPoint{X: p.Pos.X, Y: p.Pos.Y, Sector: p.Sector})
		}
		f.Cases = append(f.Cases, c)
	}

	return f
}

// TestGoldenVectors asserts that the committed vectors still describe what Step
// does — and rewrites them under -update.
//
// So a change to movement fails HERE first, loudly, telling you the file is
// stale; you regenerate; and then the TypeScript conformance test fails until
// the port is brought back into line. Two gates, in a deliberate order.
func TestGoldenVectors(t *testing.T) {
	got := buildGolden()
	path := goldenPath(t)

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		// Compact, not indented: this is a machine artefact read by a test in
		// another language, and indentation trebles a file that already lands
		// in every diff that touches movement.
		raw, err := json.Marshal(got)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(raw, '\n'), 0o600); err != nil {
			t.Fatal(err)
		}
		t.Logf("rewrote %s — the TypeScript conformance test will now fail until the port is updated", path)
		return
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v — generate it with: ./dev.sh test -run TestGoldenVectors ./internal/gamevanyadum/ -update", err)
	}
	var want goldenFile
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatal(err)
	}

	if want.Constants != got.Constants {
		t.Fatalf("constants moved: golden %+v, current %+v — regenerate with -update", want.Constants, got.Constants)
	}
	if len(want.Cases) != len(got.Cases) {
		t.Fatalf("golden has %d cases, current build has %d — regenerate with -update", len(want.Cases), len(got.Cases))
	}
	for i := range got.Cases {
		g, w := got.Cases[i], want.Cases[i]
		if len(g.Trace) != len(w.Trace) {
			t.Fatalf("case %q: trace lengths differ", g.Name)
		}
		for j := range g.Trace {
			// Exact, on this side: it is the same binary that produced the
			// file. The tolerance belongs on the TypeScript side, where a
			// different runtime's trigonometry may differ in the last bit.
			if g.Trace[j] != w.Trace[j] {
				t.Fatalf("case %q step %d: Step now produces %+v, golden says %+v — regenerate with -update",
					g.Name, j, g.Trace[j], w.Trace[j])
			}
		}
	}
}
