package gamevanyadum

import (
	"context"
	"crypto/hmac"
	crand "crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"log/slog"
	"math"
	"sync"
	"time"

	"github.com/SergeyZSpb/psycho-space/internal/db"
	"github.com/SergeyZSpb/psycho-space/internal/realtime"
	"github.com/google/uuid"
)

// The service: the one заброшка, the loop that advances it, and the single
// goroutine that writes a finished visit down.
//
// It owns exactly one World, and that world is nil whenever nobody has walked in
// yet. An idle process therefore simulates nothing at all, and the building
// every player is standing in was generated by whichever of them arrived first.

// RecentVisitsLimit bounds the "твои визиты" list on the splash screen.
const RecentVisitsLimit = 5

// Transport is the narrow slice of the realtime hub this game uses. It is an
// interface so the tests drive the whole service without a socket, and it is
// deliberately two methods wide: this game addresses its frames to connections
// and never broadcasts, because two people in one заброшка get two different
// snapshots — each frame names everybody except its own reader.
type Transport interface {
	// PublishTo sends to a single connection. An unknown connection id is a
	// no-op rather than an error — a socket may go away between the tick that
	// named it and the write.
	PublishTo(ctx context.Context, connID string, msg []byte) error
	// Members reports who is connected to a room.
	Members(ctx context.Context, room string) ([]realtime.Member, error)
}

// Service owns the world and the simulation loop that advances it.
type Service struct {
	transport Transport
	room      string
	q         db.DBTX
	repo      Repository

	mu sync.Mutex
	// world is nil when the заброшка has never been asked for, or when the last
	// person in it left. It is built on demand — by the HTTP read that serves the
	// level, or by the first hello — and torn down the moment it empties, so
	// nothing regenerates under anybody's feet.
	world *World

	// boarded is every connection that has been sent the standings and is still
	// here. A nil or missing entry reads as "this socket has never been given the
	// slot directory", which is the right starting state and the one a fresh
	// service is in.
	//
	// IT IS WHAT MAKES "A SNAPSHOT NEVER NAMES A SLOT THE STANDINGS HAVE NOT" TRUE
	// OF EVERY CONNECTION rather than of most of them. Publishing on the cadence
	// and on a roster change covers everybody who was already watching, and
	// neither fires for a NEW SOCKET belonging to somebody already in the
	// building: a reload, a tunnel coming back or a second device joins the room
	// at the upgrade and is sent snapshots naming everybody from the very next
	// tick — a whole round trip before its hello arrives, and for up to a second
	// after it. A client keeps its old directory across an outage, so a place that
	// changed hands while it was away is drawn with the PREVIOUS holder's handle
	// and interpolated from the previous holder's positions, which is precisely
	// what a slot is not allowed to cause.
	//
	// Rebuilt every tick from the connections actually served, so a socket that
	// has gone away takes its entry with it and the map cannot grow.
	boarded map[string]bool

	// publishedRoster is the world's roster version as of the last standings
	// frame sent, and −1 whenever a building has been generated and no standings
	// has gone out for it yet.
	//
	// THE SENTINEL IS LOAD-BEARING. A fresh world starts its roster at zero and
	// counts up, so carrying the previous building's number over would silently
	// suppress the first standings of the new one on the day the two happened to
	// match — a client watching a peer it had no name for, once in a while, for
	// as long as it took the once-a-second frame to arrive. ensureWorld resets
	// it, which is the one place a building is ever created.
	publishedRoster int64

	// saves carries finished visits to the writer goroutine, so the tick never
	// waits on Postgres. A full channel drops the visit and says so in the log:
	// stalling twenty-hertz simulation for everybody to record one summary is
	// the wrong trade, and the log line is what stops the loss being silent.
	saves chan Visit
	done  chan struct{}

	// pseudonymKey turns an account into the handle other players see. Minted
	// from crypto/rand at startup and held only in memory, so a pseudonym is
	// stable for one process and meaningless after a restart — a snapshot is
	// fanned out to everybody in the building, so anything in that field is a
	// handle every other player could record.
	pseudonymKey []byte
}

// pseudonymBytes is how much of the HMAC is published. Twelve base64url
// characters is more than enough to be unique among the handful of people who
// will ever share the заброшка, and short enough to cost nothing on a frame.
const pseudonymBytes = 9

// pseudonym is what other players are told an account is called.
func (s *Service) pseudonym(accountID string) string {
	mac := hmac.New(sha256.New, s.pseudonymKey)
	_, _ = mac.Write([]byte(accountID))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil)[:pseudonymBytes])
}

const savesBuffer = 64

// NewService builds the game.
func NewService(transport Transport, room string, q db.DBTX, repo Repository) *Service {
	return &Service{
		transport: transport,
		room:      room,
		q:         q,
		repo:      repo,
		saves:     make(chan Visit, savesBuffer),
		done:      make(chan struct{}),
		// Since Go 1.24 crypto/rand.Read cannot fail — it panics internally
		// rather than returning an error — so there is no error path here to
		// thread back to main.
		pseudonymKey: randomKey(),
	}
}

func randomKey() []byte {
	k := make([]byte, 32)
	_, _ = crand.Read(k)
	return k
}

// Done is closed once Run has returned and the last write has been attempted, so
// the composition root can wait for it during shutdown.
func (s *Service) Done() <-chan struct{} { return s.done }

// Config is the served catalogue.
func (s *Service) Config() Config { return BuildConfig() }

// Run advances the world on the injected tick.
//
// The tick is a parameter rather than a ticker built here (ADR-034's rule,
// applied again): main passes a time.Ticker, and every test passes a channel it
// fires by hand — which is what keeps the simulation tests free of sleeps and
// makes "advance exactly one hundred steps" a thing a test can say.
func (s *Service) Run(ctx context.Context, tick <-chan time.Time) {
	defer close(s.done)
	go s.persistVisits(ctx)

	for {
		select {
		case <-ctx.Done():
			return
		case now := <-tick:
			s.step(ctx, now)
		}
	}
}

// outbound is one frame waiting for the lock to be released.
type outbound struct {
	connID string
	msg    []byte
}

// step is one simulation tick.
//
// The publishing is deliberately done AFTER the lock is released. PublishTo hands
// the message to the hub's own goroutine, and holding this mutex across that
// would couple the simulation to the hub's queue — so the locked section only
// ever builds bytes.
//
// AN EMPTY BUILDING IS NOT ADVANCED AND NOT TORN DOWN, and the two halves of
// that are for different reasons. Not advanced, because there is nobody to
// simulate for and nobody to tell. Not torn down, because a world with nobody in
// it is the ordinary state between somebody fetching the level over HTTP and
// their socket saying hello — destroying it in that gap would hand them a
// building whose id no longer matches the geometry they just downloaded, for
// ever. Teardown belongs to the tick that takes the LAST occupant out, below.
func (s *Service) step(ctx context.Context, now time.Time) {
	conns := s.connsByAccount(ctx)

	s.mu.Lock()
	w := s.world
	if w == nil || w.Occupants() == 0 {
		// Nobody is in the building, so nobody has been told anything about it.
		// Whoever is holding a socket is boarded again on the tick they become an
		// occupant, which is the same rule the ledger runs on below.
		clear(s.boarded)
		s.mu.Unlock()
		return
	}

	// Everybody with a connection is present, whether or not they sent anything.
	// A player standing perfectly still sends nothing at all.
	for account := range conns {
		w.Seen(account, now)
	}

	for _, o := range w.Advance(SimStep.Seconds(), now) {
		s.finish(w, o)
	}
	if w.Occupants() == 0 {
		// The last person has gone. The building is dropped entirely, so the
		// next arrival generates a fresh seed rather than walking into a
		// заброшка somebody else already emptied.
		s.world = nil
	}

	// The standings, when one is due. ONE FRAME FOR EVERYBODY: it describes the
	// building rather than one person's view of it, so it is marshalled once here
	// and the same bytes are written to every connection — where a snapshot has
	// to be built per occupant because each names everybody except its own reader.
	//
	// TWO REASONS TO SEND ONE TO EVERYBODY, and the second is not a nicety. Once a
	// second is the rate the readout is for; the roster having CHANGED is the
	// correctness half, because the snapshot below addresses peers by slot and a
	// client that has not been told whose slot that is can neither label the
	// figure nor tell that the place has changed hands since it last drew it.
	//
	// Both are about the BUILDING changing, so both go to the whole of it. What
	// neither covers is a CONNECTION that has never been told anything, and that
	// is the ledger's job below.
	var board []byte
	if w.Tick%standingsEvery == 0 || w.RosterVersion() != s.publishedRoster {
		if raw, err := json.Marshal(w.Standings(now)); err == nil {
			board = raw
			s.publishedRoster = w.RosterVersion()
		}
	}

	// One snapshot PER OCCUPANT, not one per world: a frame names everybody
	// except its reader, so two people in one building get two different frames.
	var out []outbound
	// directory is the same frame for a connection that has never been sent one,
	// on a tick where none was due. Marshalled at most once per tick, and only if
	// somebody needs it — which is a handful of times in a session, not per tick.
	var directory []byte
	boarded := make(map[string]bool, len(conns))
	for account, cs := range conns {
		frame, ok := w.SnapshotFor(account)
		if !ok {
			// A connection whose ACCOUNT is not in the building: nobody on it has
			// said hello yet, or the occupant behind it was just taken out.
			// Nothing is sent a snapshot here, so nothing is sent the standings
			// either — these frames go to the people in the заброшка, not to
			// everybody holding a socket. Nor does the connection enter the
			// ledger, so the tick that does put it in the building is still a
			// first time.
			continue
		}
		msg, err := json.Marshal(frame)
		if err != nil {
			continue
		}
		for _, c := range cs {
			line := board
			if line == nil && !s.boarded[c] {
				if directory == nil {
					if raw, err := json.Marshal(w.Standings(now)); err == nil {
						directory = raw
					}
				}
				line = directory
			}
			// The standings goes FIRST on each connection. The hub writes a
			// connection's queue in order, so this is what makes "a snapshot
			// never names a slot the newest standings did not" true at the far
			// end and not merely at this one.
			if line != nil {
				out = append(out, outbound{c, line})
			}
			// A marshalling failure leaves the connection unboarded rather than
			// silently boarded, so the next tick tries again.
			boarded[c] = line != nil || s.boarded[c]
			out = append(out, outbound{c, msg})
		}
	}
	s.boarded = boarded
	s.mu.Unlock()

	s.publish(ctx, out)
}

// publish writes every queued frame, giving up on a hub that has gone away.
func (s *Service) publish(ctx context.Context, out []outbound) {
	for _, o := range out {
		if err := s.transport.PublishTo(ctx, o.connID, o.msg); err != nil {
			if errors.Is(err, realtime.ErrHubClosed) || errors.Is(err, context.Canceled) {
				return
			}
		}
	}
}

// connsByAccount groups the room's members by the account behind them, so a
// player with the game open on two devices sees the same world on both.
func (s *Service) connsByAccount(ctx context.Context) map[string][]string {
	members, err := s.transport.Members(ctx, s.room)
	if err != nil {
		return nil
	}
	out := make(map[string][]string, len(members))
	for _, m := range members {
		out[m.AccountID] = append(out[m.AccountID], m.ConnID)
	}
	return out
}

// finish queues somebody's visit for writing. It is called with the lock held.
func (s *Service) finish(w *World, o *Occupant) {
	accountID, err := uuid.Parse(o.AccountID)
	if err != nil {
		return
	}
	v := Visit{
		ID:        uuid.New(),
		AccountID: accountID,
		Seed:      w.Level.Seed,
		JoinedAt:  o.JoinedAt,
		Seconds:   o.Stayed(),
		// What he COLLECTED, which the column means (migrations/015, immutable)
		// and which nothing in the building can take back off him: no counter is
		// ever spent, so what he is carrying when he leaves is exactly what he
		// found (world.go, Occupant.bag).
		Beer: o.bag["beer"],
	}
	select {
	case s.saves <- v:
	default:
		slog.Warn("gamevanyadum: visit dropped, save queue full", "visit_id", v.ID)
	}
}

// persistVisits is the one writer. It owns every INSERT this game makes, which is
// what lets the simulation loop above promise never to touch Postgres.
func (s *Service) persistVisits(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			// Drain what is already queued before going away — a deploy in the
			// middle of somebody walking out should still record the visit. The
			// context is gone, so the writes get a fresh short-lived one.
			for {
				select {
				case v := <-s.saves:
					s.writeVisit(context.WithoutCancel(ctx), v)
				default:
					return
				}
			}
		case v := <-s.saves:
			s.writeVisit(ctx, v)
		}
	}
}

func (s *Service) writeVisit(ctx context.Context, v Visit) {
	wctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := s.repo.InsertVisit(wctx, s.q, v); err != nil {
		slog.ErrorContext(ctx, "gamevanyadum: insert visit", "err", err, "visit_id", v.ID)
	}
}

// ensureWorld returns the building, generating one if there is none. Called with
// the lock held.
//
// The seed comes from crypto/rand rather than from the clock or from a counter.
// It is not a security value, but a clock-seeded level means two buildings
// generated in the same second are the same building, and a counter means they
// arrive in a fixed order — both of which are worse than free randomness.
func (s *Service) ensureWorld() *World {
	if s.world != nil {
		return s.world
	}
	var b [8]byte
	// Since Go 1.24 crypto/rand.Read cannot fail — it panics internally rather
	// than returning an error — so there is no error path to thread out.
	_, _ = crand.Read(b[:])
	// Masked to sixty-three bits so the seed is always non-negative. It loses one
	// bit of a value that only has to be unlikely to repeat, and it buys a seed
	// that reads sensibly in a database row and in a URL somebody pastes into a
	// chat to say "we played this one".
	seed := int64(binary.LittleEndian.Uint64(b[:]) & math.MaxInt64)
	s.world = NewWorld(uuid.New(), seed)
	// A version no world can have, so the first tick of this building always
	// publishes a standings frame. See the field.
	s.publishedRoster = -1
	return s.world
}

// World is the заброшка everybody is in: which one it is, and the whole level to
// build meshes from. It generates one if nobody has been here yet, so this
// endpoint never answers "there is no building".
//
// The level is a pure function of its seed and is never written to after it is
// generated, so the caller may serialise it after the lock has been released.
// The world id is what makes that safe over time as well as at this instant: a
// client that comes back holding an id the building no longer has knows its
// geometry is stale, and fetches again.
func (s *Service) World() (uuid.UUID, *Level) {
	s.mu.Lock()
	defer s.mu.Unlock()
	w := s.ensureWorld()
	return w.ID, w.Level
}

// RecentVisits reads an account's own last visits.
func (s *Service) RecentVisits(ctx context.Context, accountID uuid.UUID) ([]Visit, error) {
	return s.repo.RecentVisits(ctx, s.q, accountID, RecentVisitsLimit)
}

// PurgeAccount takes an account out of the building WITHOUT recording anything.
//
// It is the admin «забыть» path, and three properties are load-bearing because
// of how it is called: it runs TWICE around the anonymising statement, so it
// must be idempotent; it is called for accounts that have never played, so an
// unknown one is a no-op rather than an error; and it runs on an HTTP handler's
// goroutine, so it must not block on the tick, on the hub or on Postgres.
//
// A visit belonging to somebody who is being erased is not a result, so unlike
// the grace expiry this queues nothing.
func (s *Service) PurgeAccount(accountID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.world == nil {
		return
	}
	// Only a removal that actually happened may tear the building down. Without
	// that guard, forgetting an account who was never here would drop a world
	// somebody has just fetched the level of.
	if s.world.Remove(accountID) && s.world.Occupants() == 0 {
		s.world = nil
	}
}

// HandleInbound implements realtime.Handler. It runs on the connection's own
// read pump, after the socket's rate check, so it must not block — which is why
// input is queued for the tick rather than simulated here.
func (s *Service) HandleInbound(ctx context.Context, m realtime.Member, room string, payload []byte) {
	if room != s.room {
		return
	}
	t, in := ParseInbound(payload)
	switch t {
	case TypeHello:
		s.hello(ctx, m)
	case TypeInput:
		s.mu.Lock()
		if s.world != nil {
			s.world.Enqueue(m.AccountID, in)
		}
		s.mu.Unlock()
	default:
		// Malformed, unknown or invalid: no reply and no log line. A log per bad
		// frame at the permitted ten a second is a flood lever handed to any
		// client.
	}
}

// hello walks the connection's account into the заброшка and tells it which
// building that is, which place in it the reader holds, and how far this
// occupant's input had already counted — everything constant for the life of the
// attachment, and nothing that repeats.
//
// THE HELLO IS THE JOIN. There is no start endpoint, no lobby and no code: the
// room already carries an authenticated account, so being in the room is being
// in the building, and the socket opening is the only event there is. A second
// hello is a reconnect — the occupant is still standing where he was.
//
// A refusal is ANSWERED rather than swallowed. Silence is this game's policy for
// a frame it cannot read, but a full заброшка is a frame it read perfectly well
// and cannot honour, and a player who was told nothing would sit watching an
// empty screen deciding the game is broken.
//
// AN ACCEPTED HELLO ALSO TAKES THE CONNECTION BACK OUT OF THE STANDINGS LEDGER,
// so the next tick sends it the slot directory again. One frame per attach, and
// it covers the case the ledger cannot see for itself: a ready frame naming a
// building the client is not holding makes it re-fetch the level and throw away
// everything it had cached — the standings among it — so a connection that was
// already boarded has to be boarded again.
//
// The re-board rides the next tick, so it lands after the ready this call is
// about to publish unless a tick fires inside the few microseconds between the
// unlock below and that publish. In that case the directory is the thing thrown
// away, and the client draws UNLABELLED figures until the next once-a-second
// frame — never mislabelled ones, because what it threw away it threw away.
func (s *Service) hello(ctx context.Context, m realtime.Member) {
	s.mu.Lock()
	w := s.ensureWorld()
	o, joined := w.Join(m.AccountID, s.pseudonym(m.AccountID), time.Now())
	worldID := w.ID.String()
	slot := 0
	var seq int64
	if joined {
		slot = o.Slot
		// Read under the lock, because Enqueue advances it on whatever read pump
		// the occupant's other socket happens to be on. See Ready.Seq for what a
		// client does with it, and for why a resume hint is affordable here and
		// would not be on a snapshot.
		seq = o.highSeq
		delete(s.boarded, m.ConnID)
	}
	s.mu.Unlock()

	var (
		msg []byte
		err error
	)
	if joined {
		msg, err = json.Marshal(Ready{T: TypeReady, WorldID: worldID, Slot: slot, Seq: seq})
	} else {
		msg, err = json.Marshal(Full{T: TypeFull})
	}
	if err != nil {
		return
	}
	_ = s.transport.PublishTo(ctx, m.ConnID, msg)
}
